sudo: required

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
    - sudo chmod 755 make-all
    - sudo bash ./Installer/MainInstaller.sh
    - sudo bash ./Installer/AutoBootSetup.sh
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googlemock/src/gmock-all.cc
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googletest/src/gtest-all.cc
    - ar -rv libgmock.a gtest-all.o gmock-all.o
    - cp libgmock.a ../test/
    - cd ..

script: sudo ./make-all

language: cpp
