sudo: required

install:
    - sudo bash ./Installer/MainInstaller.sh
    - sudo bash ./Installer/AutoBootSetup.sh
    - export LD_LIBRARY_PATH=/home/opencv/lib
	- export PKG_CONFIG_PATH=/home/opencv/lib/pkgconfig

script: make

language: cpp