sudo: required

install:
    - sudo bash ./Installer/MainInstaller.sh
    - sudo bash ./Installer/AutoBootSetup.sh
    - pkg-config --modversion opencv
    - pkg-config --cflags opencv
    - pkg-config --libs opencv
    # - ls /usr/include/opencv
    - sudo updatedb
    - locate cv.h

script: make

language: cpp